mainConfig:
  type: esbuild
  path: esbuild.main.config.ts
  src: src/main/main.ts
  output:
    dir: dist/main
    filename: main.js
rendererConfig:
  type: vite
  path: src/renderer/vite.config.mts
  src: src/renderer/main.ts
  output:
    dir: dist/renderer
